/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
// Query TypeMap
import "@sanity/client";

export interface SanityImagePaletteSwatch {
	_type: "sanity.imagePaletteSwatch";
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
}

export interface SanityImagePalette {
	_type: "sanity.imagePalette";
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
}

export interface SanityImageDimensions {
	_type: "sanity.imageDimensions";
	height?: number;
	width?: number;
	aspectRatio?: number;
}

export interface SanityFileAsset {
	_id: string;
	_type: "sanity.fileAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
}

export interface Geopoint {
	_type: "geopoint";
	lat?: number;
	lng?: number;
	alt?: number;
}

export type BlockContent = (
	| {
			children?: {
				marks?: string[];
				text?: string;
				_type: "span";
				_key: string;
			}[];
			style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
			listItem?: "bullet" | "number";
			markDefs?: (
				| {
						href?: string;
						_type: "link";
						_key: string;
				  }
				| {
						reference?:
							| {
									_ref: string;
									_type: "reference";
									_weak?: boolean;
									[internalGroqTypeReferenceTo]?: "post";
							  }
							| {
									_ref: string;
									_type: "reference";
									_weak?: boolean;
									[internalGroqTypeReferenceTo]?: "author";
							  }
							| {
									_ref: string;
									_type: "reference";
									_weak?: boolean;
									[internalGroqTypeReferenceTo]?: "category";
							  };
						_type: "internalLink";
						_key: string;
				  }
			)[];
			level?: number;
			_type: "block";
			_key: string;
	  }
	| {
			asset?: {
				_ref: string;
				_type: "reference";
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
			};
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			height?: number;
			width?: number;
			_type: "image";
			_key: string;
	  }
	| ({
			_key: string;
	  } & Code)
	| ({
			_key: string;
	  } & Latex)
	| ({
			_key: string;
	  } & Mermaid)
)[];

export interface Post {
	_id: string;
	_type: "post";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	author?: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: "author";
	};
	mainImage?: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: "image";
	};
	categories?: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "category";
	}[];
	publishedAt?: string;
	body?: BlockContent;
}

export interface Category {
	_id: string;
	_type: "category";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	description?: string;
}

export interface Author {
	_id: string;
	_type: "author";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	slug?: Slug;
	image?: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: "image";
	};
	bio?: {
		children?: {
			marks?: string[];
			text?: string;
			_type: "span";
			_key: string;
		}[];
		style?: "normal";
		listItem?: never;
		markDefs?: {
			href?: string;
			_type: "link";
			_key: string;
		}[];
		level?: number;
		_type: "block";
		_key: string;
	}[];
}

export interface SanityImageCrop {
	_type: "sanity.imageCrop";
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
}

export interface SanityImageHotspot {
	_type: "sanity.imageHotspot";
	x?: number;
	y?: number;
	height?: number;
	width?: number;
}

export interface SanityImageAsset {
	_id: string;
	_type: "sanity.imageAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
}

export interface SanityAssetSourceData {
	_type: "sanity.assetSourceData";
	name?: string;
	id?: string;
	url?: string;
}

export interface SanityImageMetadata {
	_type: "sanity.imageMetadata";
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
}

export interface Slug {
	_type: "slug";
	current?: string;
	source?: string;
}

export interface Mermaid {
	_type: "mermaid";
	graph?: string;
}

export interface Latex {
	_type: "latex";
	body?: string;
}

export type Markdown = string;

export interface Code {
	_type: "code";
	language?: string;
	filename?: string;
	code?: string;
	highlightedLines?: number[];
}

export type AllSanitySchemaTypes =
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityFileAsset
	| Geopoint
	| BlockContent
	| Post
	| Category
	| Author
	| SanityImageCrop
	| SanityImageHotspot
	| SanityImageAsset
	| SanityAssetSourceData
	| SanityImageMetadata
	| Slug
	| Mermaid
	| Latex
	| Markdown
	| Code;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{    _id, title, slug, author, publishedAt, mainImage, categories, body}
export type POSTS_QUERYResult = {
	_id: string;
	title: string | null;
	slug: Slug | null;
	author: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: "author";
	} | null;
	publishedAt: string | null;
	mainImage: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: "image";
	} | null;
	categories:
		| {
				_ref: string;
				_type: "reference";
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: "category";
		  }[]
		| null;
	body: BlockContent | null;
}[];
declare module "@sanity/client" {
	interface SanityQueries {
		'*[_type == "post" && defined(slug.current)]{\n    _id, title, slug, author, publishedAt, mainImage, categories, body\n}': POSTS_QUERYResult;
	}
}
