/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
// Query TypeMap
import "@sanity/client";

export interface SanityImagePaletteSwatch {
	_type: "sanity.imagePaletteSwatch";
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
}

export interface SanityImagePalette {
	_type: "sanity.imagePalette";
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
}

export interface SanityImageDimensions {
	_type: "sanity.imageDimensions";
	height?: number;
	width?: number;
	aspectRatio?: number;
}

export interface Geopoint {
	_type: "geopoint";
	lat?: number;
	lng?: number;
	alt?: number;
}

export interface Project {
	_id: string;
	_type: "project";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	description: string;
	tags: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "category";
	}[];
	publishedAt: string;
	source?: string;
	demo?: string;
	image: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: "image";
	};
}

export interface Profile {
	_id: string;
	_type: "profile";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name: string;
	caption: string;
	bio: string;
	image: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: "image";
	};
	languages: string[];
	resume: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.fileAsset";
		};
		_type: "file";
	};
	contact: {
		discord?: string;
		linkedin: string;
		email: string;
	};
	education: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "education";
	}[];
	experience: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "experience";
	}[];
	projects: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "project";
	}[];
	technologies: string[];
}

export interface SanityFileAsset {
	_id: string;
	_type: "sanity.fileAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
}

export interface Experience {
	_id: string;
	_type: "experience";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	company: string;
	role: string;
	startDate: string;
	endDate?: string;
	description?: string;
	points?: string[];
	icon: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: "image";
	};
	subExperiences?: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "experience";
	}[];
}

export interface Education {
	_id: string;
	_type: "education";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	institution: string;
	degree: string;
	startDate: string;
	endDate?: string;
	description?: string;
	icon: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: "image";
	};
}

export interface Post {
	_id: string;
	_type: "post";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	author: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: "author";
	};
	mainImage: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		_type: "image";
	};
	categories: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "category";
	}[];
	publishedAt: string;
	excerpt: string;
	body: string;
}

export interface Author {
	_id: string;
	_type: "author";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name: string;
	slug: Slug;
	image: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: "image";
	};
	bio: {
		children?: {
			marks?: string[];
			text?: string;
			_type: "span";
			_key: string;
		}[];
		style?: "normal";
		listItem?: never;
		markDefs?: {
			href?: string;
			_type: "link";
			_key: string;
		}[];
		level?: number;
		_type: "block";
		_key: string;
	}[];
}

export interface SanityImageCrop {
	_type: "sanity.imageCrop";
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
}

export interface SanityImageHotspot {
	_type: "sanity.imageHotspot";
	x?: number;
	y?: number;
	height?: number;
	width?: number;
}

export interface SanityImageAsset {
	_id: string;
	_type: "sanity.imageAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
}

export interface SanityAssetSourceData {
	_type: "sanity.assetSourceData";
	name?: string;
	id?: string;
	url?: string;
}

export interface SanityImageMetadata {
	_type: "sanity.imageMetadata";
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
}

export interface Category {
	_id: string;
	_type: "category";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	description?: string;
}

export interface Slug {
	_type: "slug";
	current: string;
	source?: string;
}

export type Markdown = string;

export type AllSanitySchemaTypes =
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| Geopoint
	| Project
	| Profile
	| SanityFileAsset
	| Experience
	| Education
	| Post
	| Author
	| SanityImageCrop
	| SanityImageHotspot
	| SanityImageAsset
	| SanityAssetSourceData
	| SanityImageMetadata
	| Category
	| Slug
	| Markdown;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post"    && defined(slug.current)    && (!defined($search) || $search == "" || (title match $search || body match $search))    && (!defined($tags) || count($tags) == 0 || array::intersects(categories[]->slug.current, $tags))    ] | order(publishedAt desc) {        _id, title, slug, publishedAt, mainImage, excerpt, author->{name, image}, categories[]->{title, slug, description}    }
export type POSTS_QUERYResult = {
	_id: string;
	title: string;
	slug: Slug;
	publishedAt: string;
	mainImage: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		_type: "image";
	};
	excerpt: string;
	author: {
		name: string;
		image: {
			asset?: {
				_ref: string;
				_type: "reference";
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
			};
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: "image";
		};
	};
	categories: {
		title: string;
		slug: Slug;
		description: string | null;
	}[];
}[];
// Variable: POST_QUERY
// Query: *[_type == "post" && defined(slug.current) && slug.current == $slug][0] {        _id, title, slug, publishedAt, mainImage, author->{name, image}, categories[]->{title, slug, description}, body    }
export type POST_QUERYResult = {
	_id: string;
	title: string;
	slug: Slug;
	publishedAt: string;
	mainImage: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		_type: "image";
	};
	author: {
		name: string;
		image: {
			asset?: {
				_ref: string;
				_type: "reference";
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
			};
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: "image";
		};
	};
	categories: {
		title: string;
		slug: Slug;
		description: string | null;
	}[];
	body: string;
} | null;
// Variable: PREV_NEXT_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current) && slug.current == $slug][0] {        "prev": *[_type == "post" && defined(slug.current) && defined(publishedAt) && publishedAt < ^.publishedAt]            | order(publishedAt desc)[0] {                _id, title, slug, excerpt, publishedAt        },        "next": *[_type == "post" && defined(slug.current) && defined(publishedAt) && publishedAt > ^.publishedAt]            | order(publishedAt asc)[0] {                _id, title, slug, excerpt, publishedAt        }    }
export type PREV_NEXT_POSTS_QUERYResult = {
	prev: {
		_id: string;
		title: string;
		slug: Slug;
		excerpt: string;
		publishedAt: string;
	} | null;
	next: {
		_id: string;
		title: string;
		slug: Slug;
		excerpt: string;
		publishedAt: string;
	} | null;
} | null;
// Variable: RECENT_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(_createdAt desc)[0...$limit] {        _id, title, slug, publishedAt, mainImage, categories[]->{title, slug, description}, excerpt, author->{name, image}    }
export type RECENT_POSTS_QUERYResult = {
	_id: string;
	title: string;
	slug: Slug;
	publishedAt: string;
	mainImage: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		_type: "image";
	};
	categories: {
		title: string;
		slug: Slug;
		description: string | null;
	}[];
	excerpt: string;
	author: {
		name: string;
		image: {
			asset?: {
				_ref: string;
				_type: "reference";
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
			};
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: "image";
		};
	};
}[];
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] {        _id, title, slug, description    }
export type CATEGORIES_QUERYResult = {
	_id: string;
	title: string;
	slug: Slug;
	description: string | null;
}[];
declare module "@sanity/client" {
	interface SanityQueries {
		'\n    *[_type == "post"\n    && defined(slug.current)\n    && (!defined($search) || $search == "" || (title match $search || body match $search))\n    && (!defined($tags) || count($tags) == 0 || array::intersects(categories[]->slug.current, $tags))\n    ] | order(publishedAt desc) {\n        _id, title, slug, publishedAt, mainImage, excerpt, author->{name, image}, categories[]->{title, slug, description}\n    }': POSTS_QUERYResult;
		'\n    *[_type == "post" && defined(slug.current) && slug.current == $slug][0] {\n        _id, title, slug, publishedAt, mainImage, author->{name, image}, categories[]->{title, slug, description}, body\n    }': POST_QUERYResult;
		'\n    *[_type == "post" && defined(slug.current) && slug.current == $slug][0] {\n        "prev": *[_type == "post" && defined(slug.current) && defined(publishedAt) && publishedAt < ^.publishedAt]\n            | order(publishedAt desc)[0] {\n                _id, title, slug, excerpt, publishedAt\n        },\n        "next": *[_type == "post" && defined(slug.current) && defined(publishedAt) && publishedAt > ^.publishedAt]\n            | order(publishedAt asc)[0] {\n                _id, title, slug, excerpt, publishedAt\n        }\n    }\n': PREV_NEXT_POSTS_QUERYResult;
		'\n    *[_type == "post" && defined(slug.current)] | order(_createdAt desc)[0...$limit] {\n        _id, title, slug, publishedAt, mainImage, categories[]->{title, slug, description}, excerpt, author->{name, image}\n    }': RECENT_POSTS_QUERYResult;
		'\n    *[_type == "category"] {\n        _id, title, slug, description\n    }': CATEGORIES_QUERYResult;
	}
}
